# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: xm-task:latest
        container_name: app
        volumes:
            - './:/var/www'
        networks:
            - internal

    worker:
        image: xm-task:latest
        volumes:
            - './:/var/www'
        container_name: worker
        networks:
            - internal
        command: php bin/console messenger:consume -vv
        depends_on:
            - app
            - redis

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - './:/var/www'
            - './nginx/conf.d:/etc/nginx/conf.d'
        networks:
            - internal
        depends_on:
            - app

    redis:
        image: redis:latest
        volumes:
            - redis-volume:/data
        networks:
            - internal

networks:
    internal:
        driver: bridge

volumes:
    redis-volume:
        driver: local

